first_name_field_loc = "#firstname"
last_name_field_loc = "#lastname"
email_field_loc = "#email_address"
password_field_loc = "#password"
password_confirmation_loc = "#password-confirmation"
button_create_an_account = ".action.submit.primary"
success_message_loc = "//div[@class='message-success success message']/div"
error_message_password_8symbols_loc = "//div[@id='password-error']"

menu_loc = ".filter-options-title"
style_menu_tee_loc = "((//div[@class='filter-options-content'])[2]/ol/li/a)[8]"
size_menu_XL_loc = "//a/div[contains(text(), 'XL')]"
climate_menu_indoor_loc = "((//div[@class='filter-options-content'])/ol/li/a)[2]"
color_menu_blue_loc = "(//div[@class='filter-options-content']/div/div/a/div)[2]"
color_tee_first_wight_loc = "(//div[@class='swatch-attribute color']/div/div)[3]"

now_shopping_by_number_loc = "//strong[@data-count='4']"
message_add_to_comparison_list_loc = "//div[contains(@data-bind, 'html: $parent.prepareMessageForHtml(message.text)')]"
filter_current_items_loc = ".filter-current .items .item"
filter_label_loc = ".filter-label"
filter_value_loc = ".filter-value"
button_comparison_list_loc = "//div[@class='message-success success message']/div/a"
product_items_loc = "//button/span[contains(text(), 'Add to Cart')]"
